Return correct headers for JSON and Javascript responses.
vanilla/wordpress-vanilla pull request #32
Opened 2019-11-21 23:01 UTC by nervoustwit

Presently when trying to use WordPress to authenticate SSO connections for forums we are not returning the proper content-type headers. This PR will fix it. 

This will possibly solve this issue: https://github.com/vanilla/support/issues/1073

2019-11-22 05:39 UTC, tburry requested changes

2019-11-22 05:39 UTC, tburry commented on functions.jsconnect.php
> +        safeHeader('Content-Type: application/javascript; charset=utf-8', true);
I think you need to bring the `safeHeader()` function into this library.

2019-11-22 05:41 UTC, tburry commented
You can see if this is the case by making a non-wp jsConnect response return the correct and incorrect headers. I recommend doing that test to confirm because doing this update will take some time.

2019-11-27 15:49 UTC, initvector approved these changes
I have not tested this change, but the update seems simple, straightforward and limited in scope.

2019-11-27 15:57 UTC, danni-stark approved these changes

2019-11-27 17:00 UTC, tburry approved these changes

2019-11-27 17:00 UTC, merged